# Generated by Django 5.2 on 2025-04-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='biggestConcept',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='nextClosestDoc',
        ),
    ]
